env:
  browser: true
  es6: true
  node: true
extends: 'airbnb'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  parser: "babel-eslint"
plugins:
  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  react/jsx-filename-extension: 
    - warn
    - extensions:
    - ".js" 
    - ".jsx"
